services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: npm run start:prod
